### PR TITLE
Fix handling of international characters

### LINKED ISSUE #33: 'ñ' causes a capitalization bug
Hi,

I noticed this while using this module today:

`
title('diseño') // 'DiseñO'
`

Using 'ñ' results in the next letter being capitalized. I haven't dug to figure out what's causing this, but I just wanted to surface the problem. Thanks for all the hard work.

### PR DESCRIPTION
**Pull request by SeriousBug**
The character class `\w` only matches ASCII characters. By replacing it with a more permissive negated set, international (unicode) characters are handled correctly.

Added tests for these international characters. All these tests fail without this fix.

Fixes #33

Let me know if there's any changes I can do to help this get merged.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -93,3 +93,16 @@ test("should capitalize the last word regardless of syntax", t => {
...
+  let from = "çeşme city"
+  let to = "Çeşme City"
+  t.is(title(from), to)
+
+  from = "la niña esta aquí"
+  to = "La Niña Esta Aquí"
+  t.is(title(from), to)
+
+  from = "forhandlingsmøde"
+  to = "Forhandlingsmøde"
```
Comment (dferber90) [inline test/index.js:107]: I just stumbled upon this, and it seems like the `t.is` call is missing here :)

Comment (SeriousBug) [reply test/index.js:107]: Oops :) Thanks for catching that, fixed it!

**Comment by SeriousBug** [comment]
Hey @leo @leerob, sorry to bother you and apologies if you are not the right folks to ping. Could someone please give this PR a review when possible? I'd love to get this merged within this week if we can. Again, please let me know if there are any changes needed to get it merged.

**Comment by meikidd** [comment]
Thanks a lot @SeriousBug . I would be great if this PR can get merged

**Comment by meikidd** [comment]
Hi @leo @leerob, it would be great if you can take a look at this PR, really appreciate it. And sorry to bother if you are not the ones to ping.

**Comment by SeriousBug** [comment]
@meikidd @dferber90

We forked the repo and applied this fix here: https://www.npmjs.com/package/@dendronhq/title
Repo: https://github.com/dendronhq/title/

We'll close the fork once this PR is merged, but it's up for anyone who might find it useful in the meantime.

**Comment by meikidd** [comment]
Thanks @SeriousBug.

@leo @sergiodxa @leerob Sorry to pin you again, could you have a check on this PR, thanks a lot!

**Comment by meikidd** [comment]
Hi @leerob @leo @sergiodxa, could we have this pr merged if possible, it will fix #33 and #63, really appreciate it.

**Review by dferber90 — APPROVED** [review]

**Comment by meikidd** [comment]
Thank you so much @dferber90 @leerob
